In [1]:
from torchvision.models import efficientnet_b0, EfficientNet_B0_Weights
import torch
import pandas as pd
import os
from utils.dataset import PandasDataset
from utils.models import EfficientNetApi
from utils.metrics import evaluation, format_metrics

In [2]:
ROOT_DIR = '../../..'

data_dir = '../../../../dataset'
images_dir = os.path.join(data_dir, 'tiles')
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

cuda


In [3]:
df_test = pd.read_csv(f"{ROOT_DIR}/data/val.csv")
test_dataset = PandasDataset(images_dir, df_test, transforms=None)
test_loader = torch.utils.data.DataLoader(test_dataset, batch_size=2)

In [4]:

for model_name in ["b0-entropy.pth","b0-entropy-00.pth", "b0-entropy-50.pth", "b0-entropy-100.pth"]:
    load_model = efficientnet_b0(weights=EfficientNet_B0_Weights.DEFAULT)
    model = EfficientNetApi(model=load_model, output_dimensions=5, dropout_rate=0.6)
    model = model.to(device)
    model.load_state_dict(
        torch.load(f"models/{model_name}")
    )
    response = evaluation(model, test_loader, device)
    result = format_metrics(response[0])
    print(f"==================================== {model_name}==============")
    print(result)

100%|██████████| 797/797 [01:20<00:00,  9.86it/s]


==================================== b0-entropy.pth==============
VAL_ACC      Mean: 66.759 | Std: 1.102 | 95% CI: [64.972, 68.550]
VAL_KAPPA    Mean: 0.866 | Std: 0.010 | 95% CI: [0.848, 0.882]
VAL_F1       Mean: 0.616 | Std: 0.012 | 95% CI: [0.596, 0.636]
VAL_RECALL   Mean: 0.622 | Std: 0.012 | 95% CI: [0.602, 0.642]
VAL_PRECISION Mean: 0.616 | Std: 0.012 | 95% CI: [0.596, 0.635]


100%|██████████| 797/797 [01:19<00:00, 10.02it/s]


==================================== b0-entropy-00.pth==============
VAL_ACC      Mean: 64.618 | Std: 1.185 | 95% CI: [62.649, 66.604]
VAL_KAPPA    Mean: 0.856 | Std: 0.011 | 95% CI: [0.837, 0.874]
VAL_F1       Mean: 0.593 | Std: 0.013 | 95% CI: [0.573, 0.614]
VAL_RECALL   Mean: 0.592 | Std: 0.013 | 95% CI: [0.572, 0.613]
VAL_PRECISION Mean: 0.616 | Std: 0.012 | 95% CI: [0.597, 0.636]


100%|██████████| 797/797 [01:17<00:00, 10.22it/s]


==================================== b0-entropy-50.pth==============
VAL_ACC      Mean: 62.681 | Std: 1.232 | 95% CI: [60.640, 64.658]
VAL_KAPPA    Mean: 0.843 | Std: 0.011 | 95% CI: [0.824, 0.862]
VAL_F1       Mean: 0.568 | Std: 0.013 | 95% CI: [0.546, 0.589]
VAL_RECALL   Mean: 0.570 | Std: 0.013 | 95% CI: [0.548, 0.590]
VAL_PRECISION Mean: 0.593 | Std: 0.013 | 95% CI: [0.570, 0.614]


100%|██████████| 797/797 [01:20<00:00,  9.88it/s]


==================================== b0-entropy-100.pth==============
VAL_ACC      Mean: 62.606 | Std: 1.167 | 95% CI: [60.703, 64.470]
VAL_KAPPA    Mean: 0.837 | Std: 0.012 | 95% CI: [0.817, 0.856]
VAL_F1       Mean: 0.569 | Std: 0.013 | 95% CI: [0.549, 0.591]
VAL_RECALL   Mean: 0.569 | Std: 0.012 | 95% CI: [0.549, 0.591]
VAL_PRECISION Mean: 0.578 | Std: 0.013 | 95% CI: [0.557, 0.600]


In [4]:
df_test = pd.read_csv(f"{ROOT_DIR}/data/test.csv")
test_dataset = PandasDataset(images_dir, df_test, transforms=None)
test_loader = torch.utils.data.DataLoader(test_dataset, batch_size=2)

model_name = "b0-entropy.pth"
load_model = efficientnet_b0(weights=EfficientNet_B0_Weights.DEFAULT)
model = EfficientNetApi(model=load_model, output_dimensions=5, dropout_rate=0.6)
model = model.to(device)
model.load_state_dict(
    torch.load(f"models/{model_name}")
)
response = evaluation(model, test_loader, device)

100%|██████████| 796/796 [01:20<00:00,  9.90it/s]


In [5]:
result = format_metrics(response[0])
print(response[0])
print(result)

{'val_acc': {'mean': np.float64(0.6291670860052109), 'std': np.float64(0.012082365025390398), 'ci_5': np.float64(0.6099246144294739), 'ci_95': np.float64(0.648900744318962)}, 'val_kappa': {'mean': np.float64(0.8331026954281615), 'std': np.float64(0.011734696001909855), 'ci_5': np.float64(0.8132342733485342), 'ci_95': np.float64(0.8516192144555225)}, 'val_f1': {'mean': np.float64(0.5739082917571068), 'std': np.float64(0.012509502375393208), 'ci_5': np.float64(0.5543501019477844), 'ci_95': np.float64(0.5939930558204651)}, 'val_recall': {'mean': np.float64(0.5800507892370224), 'std': np.float64(0.012550271902054561), 'ci_5': np.float64(0.5604120761156082), 'ci_95': np.float64(0.6001979827880859)}, 'val_precision': {'mean': np.float64(0.5732575584650039), 'std': np.float64(0.012586676861375302), 'ci_5': np.float64(0.554021742939949), 'ci_95': np.float64(0.5938588559627532)}, 'mean_error': {'mean': np.float64(0.5303655776977539), 'std': np.float64(0.02119443058806211), 'ci_5': np.float64(0.

In [6]:
print(response[0].get("confusion_matrix"))

[[0.88206291 0.06912467 0.01604459 0.01872705 0.00932608 0.0047147 ]
 [0.14996741 0.60530338 0.18966443 0.04494922 0.01011557 0.        ]
 [0.01982847 0.19210694 0.44806034 0.20968549 0.09035403 0.03996473]
 [0.02757052 0.03738755 0.14566393 0.38079889 0.26287489 0.14570422]
 [0.05879954 0.03171242 0.04828324 0.1088009  0.49517895 0.25722494]
 [0.04353617 0.00559653 0.00539401 0.05917468 0.21739835 0.66890026]]
